version: "3.4"

services:
  # Planetscale local
  planetscale:
    build:
      context: .
    container_name: upstash_redis_local
    hostname: upstash-redis-local
    depends_on:
      - redis
    ports:
      - 3000:8080
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379
  # Redis
  redis:
    image: redis:6.2.6
    hostname: redis
    command: redis-server --save 60 1 --loglevel warning
